import http from "node:http";
import { Server } from "socket.io";
import jwt from "jsonwebtoken";
import { app } from "./app.js";
import { config } from "./config.js";
import { setIO } from "./socket.js";
const server=http.createServer(app);
const io=new Server(server,{cors:{origin:config.CLIENT_URL}});
io.use((socket,next)=>{try{jwt.verify(socket.handshake.auth.token,config.JWT_SECRET);next();}catch{next(new Error("Unauthorized"));}});
io.on("connection",socket=>socket.on("project:join",(projectId:string)=>socket.join(`project:${projectId}`)));
setIO(io);
server.listen(config.PORT,()=>console.log(`TeamFlow API listening on http://localhost:${config.PORT}`));
