import {useEffect,useState} from "react";
import {Navigate,Route,Routes,useNavigate,useParams} from "react-router-dom";
import {io} from "socket.io-client";
import {api,API_URL,Project,Task,User} from "./api";

function Auth({mode}:{mode:"login"|"register"}){
 const nav=useNavigate(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));
  try{const out=await api<{token:string;user:User}>(`/auth/${mode}`,{method:"POST",body:JSON.stringify(data)});localStorage.setItem("token",out.token);localStorage.setItem("user",JSON.stringify(out.user));nav("/");}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="auth"><section className="auth-copy"><div className="logo">TEAMFLOW</div><h1>Work moves better<br/>when everyone can see it.</h1><p>A focused project board for teams that value clarity.</p></section><form className="panel auth-form" onSubmit={submit}><span className="eyebrow">{mode==="login"?"WELCOME BACK":"JOIN THE TEAM"}</span><h2>{mode==="login"?"Sign in":"Create account"}</h2>{mode==="register"&&<label>Name<input name="name" minLength={2} required placeholder="Your name"/></label>}<label>Email<input name="email" type="email" required placeholder="you@company.com"/></label><label>Password<input name="password" type="password" minLength={8} required placeholder="At least 8 characters"/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button><p className="switch">{mode==="login"?<>New here? <a href="/register">Create an account</a></>:<>Already a member? <a href="/login">Sign in</a></>}</p></form></main>
}
function Layout({children}:{children:React.ReactNode}){const user=JSON.parse(localStorage.getItem("user")||"null") as User|null;const nav=useNavigate();return <><header><a className="logo" href="/">TEAMFLOW</a><div className="profile"><span className="avatar">{user?.name?.[0]}</span><span><b>{user?.name}</b><small>{user?.role}</small></span><button className="ghost" onClick={()=>{localStorage.clear();nav("/login")}}>Sign out</button></div></header>{children}</>}
function Projects(){
 const user=JSON.parse(localStorage.getItem("user")||"null") as User,[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(search=""){setLoading(true);try{setProjects((await api<{items:Project[]}>(`/projects?search=${encodeURIComponent(search)}`)).items)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));try{await api("/projects",{method:"POST",body:JSON.stringify(d)});f.reset();load()}catch(e){setError((e as Error).message)}}
 return <Layout><main className="page"><div className="title-row"><div><span className="eyebrow">YOUR WORKSPACE</span><h1>Projects</h1><p>Everything your team is moving forward.</p></div><input className="search" placeholder="Search projects…" onChange={e=>load(e.target.value)}/></div>{user.role==="ADMIN"&&<form className="quick-create panel" onSubmit={create}><input name="name" required minLength={2} placeholder="New project name"/><input name="description" placeholder="What is this project about?"/><button>Create project</button></form>}{error&&<div className="error">{error}</div>}{loading?<div className="state">Loading projects…</div>:projects.length===0?<div className="state">No projects yet. Create the first one.</div>:<div className="project-grid">{projects.map(p=><a className="project-card" href={`/projects/${p.id}`} key={p.id}><span className="project-mark">{p.name[0]}</span><h3>{p.name}</h3><p>{p.description||"No description"}</p><div className="metrics"><span>{p._count?.tasks||0} tasks</span><span>{p._count?.members||0} members</span></div></a>)}</div>}</main></Layout>
}
const columns=[["TODO","To do"],["IN_PROGRESS","In progress"],["DONE","Done"]] as const;
function Board(){
 const {id}=useParams(),[project,setProject]=useState<Project>(),[tasks,setTasks]=useState<Task[]>([]),[members,setMembers]=useState<User[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Task|null>(null);
 async function load(){try{const [p,t,m]=await Promise.all([api<Project>(`/projects/${id}`),api<{items:Task[]}>(`/projects/${id}/tasks?limit=100`),api<User[]>(`/projects/${id}/users`)]);setProject(p);setTasks(t.items);setMembers(m)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load();const s=io(API_URL,{auth:{token:localStorage.getItem("token")}});s.emit("project:join",id);s.on("task:created",load);s.on("task:updated",load);s.on("task:deleted",load);return()=>{s.disconnect()}},[id]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,raw=Object.fromEntries(new FormData(f));const data={...raw,assigneeId:raw.assigneeId||null,dueDate:new Date(String(raw.dueDate)).toISOString()};try{await api(`/projects/${id}/tasks${editing?`/${editing.id}`:""}`,{method:editing?"PATCH":"POST",body:JSON.stringify(data)});setEditing(null);f.reset();load()}catch(e){setError((e as Error).message)}}
 async function move(task:Task,status:Task["status"]){await api(`/projects/${id}/tasks/${task.id}`,{method:"PATCH",body:JSON.stringify({status})});load()}
 if(loading)return <Layout><div className="state">Loading board…</div></Layout>;
 return <Layout><main className="page board-page"><a className="back" href="/">← All projects</a><div className="title-row"><div><span className="eyebrow">PROJECT BOARD</span><h1>{project?.name}</h1><p>{project?.description}</p></div></div>{error&&<div className="error">{error}</div>}<form className="task-form panel" onSubmit={save}><input name="title" required minLength={2} placeholder="What needs to be done?" defaultValue={editing?.title}/><input name="description" placeholder="Add context" defaultValue={editing?.description}/><select name="priority" defaultValue={editing?.priority||"MEDIUM"}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select><select name="assigneeId" defaultValue={editing?.assigneeId||""}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input type="date" name="dueDate" required defaultValue={editing?.dueDate.slice(0,10)}/><button>{editing?"Save changes":"Add task"}</button>{editing&&<button type="button" className="ghost" onClick={()=>setEditing(null)}>Cancel</button>}</form><div className="board">{columns.map(([value,label])=><section className="column" key={value}><div className="column-head"><h2>{label}</h2><span>{tasks.filter(t=>t.status===value).length}</span></div>{tasks.filter(t=>t.status===value).map(t=><article className="task" key={t.id}><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span><h3>{t.title}</h3><p>{t.description||"No description"}</p><div className="task-meta"><span>{t.assignee?.name||"Unassigned"}</span><time>{new Date(t.dueDate).toLocaleDateString()}</time></div><div className="task-actions"><select value={t.status} onChange={e=>move(t,e.target.value as Task["status"])}>{columns.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button className="ghost" onClick={()=>setEditing(t)}>Edit</button><button className="danger" onClick={async()=>{if(confirm("Delete this task?")){await api(`/projects/${id}/tasks/${t.id}`,{method:"DELETE"});load()}}}>Delete</button></div></article>)}</section>)}</div></main></Layout>
}
function Protected({children}:{children:React.ReactNode}){return localStorage.getItem("token")?children:<Navigate to="/login"/>}
export function App(){return <Routes><Route path="/login" element={<Auth mode="login"/>}/><Route path="/register" element={<Auth mode="register"/>}/><Route path="/" element={<Protected><Projects/></Protected>}/><Route path="/projects/:id" element={<Protected><Board/></Protected>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
