import {ForbiddenException,Injectable,NotFoundException,UnprocessableEntityException} from "@nestjs/common";
import {Prisma,Role} from "@prisma/client";
import {z} from "zod";
import {PrismaService} from "../prisma.service.js";
import {ProjectsService} from "../projects/projects.service.js";
import {TasksGateway} from "./tasks.gateway.js";
import type {AuthUser} from "../auth/auth.guard.js";
const taskFields={title:z.string().trim().min(2).max(150),description:z.string().trim().max(3000),status:z.enum(["TODO","IN_PROGRESS","DONE"]),priority:z.enum(["LOW","MEDIUM","HIGH","URGENT"]),dueDate:z.coerce.date(),assigneeId:z.string().cuid().nullable()};
const createTaskDto=z.object({...taskFields,description:taskFields.description.default(""),status:taskFields.status.default("TODO"),priority:taskFields.priority.default("MEDIUM"),assigneeId:taskFields.assigneeId.optional()}).strict();
const updateTaskDto=z.object({title:taskFields.title.optional(),description:taskFields.description.optional(),status:taskFields.status.optional(),priority:taskFields.priority.optional(),dueDate:taskFields.dueDate.optional(),assigneeId:taskFields.assigneeId.optional()}).strict();
const optionalFilter=<T extends z.ZodTypeAny>(schema:T)=>z.preprocess(value=>value===""?undefined:value,schema.optional());
const listTaskDto=z.object({search:z.string().max(100).optional().default(""),status:optionalFilter(taskFields.status),priority:optionalFilter(taskFields.priority),assigneeId:optionalFilter(z.string()),sort:z.enum(["createdAt","dueDate","title","priority","status"]).optional().default("createdAt"),order:z.enum(["asc","desc"]).optional().default("desc"),page:z.coerce.number().int().positive().optional().default(1),limit:z.coerce.number().int().min(1).max(100).optional().default(50)});
const include={creator:{select:{id:true,name:true}},assignee:{select:{id:true,name:true,email:true}}} as const;
@Injectable()
export class TasksService{
 constructor(private db:PrismaService,private projects:ProjectsService,private gateway:TasksGateway){}
 private async validateAssignee(projectId:string,userId?:string|null){if(userId&&!await this.db.projectMember.findUnique({where:{projectId_userId:{projectId,userId}}}))throw new UnprocessableEntityException("Assignee must be a project member")}
 async list(projectId:string,user:AuthUser,query:any){await this.projects.requireAccess(projectId,user);const q=listTaskDto.parse(query),{page,limit,sort,order}=q;const where:Prisma.TaskWhereInput={projectId,...(q.status?{status:q.status}:{}),...(q.priority?{priority:q.priority}:{}),...(q.assigneeId?{assigneeId:q.assigneeId==="unassigned"?null:q.assigneeId}:{}),...(q.search?{OR:[{title:{contains:q.search,mode:"insensitive"}},{description:{contains:q.search,mode:"insensitive"}}]}:{})};const[items,total]=await this.db.$transaction([this.db.task.findMany({where,include,orderBy:{[sort]:order},skip:(page-1)*limit,take:limit}),this.db.task.count({where})]);return{items,total,page,limit,pages:Math.ceil(total/limit)}}
 async create(projectId:string,user:AuthUser,body:unknown){await this.projects.requireOwnerOrAdmin(projectId,user);const data=createTaskDto.parse(body);await this.validateAssignee(projectId,data.assigneeId);const task=await this.db.task.create({data:{...data,projectId,creatorId:user.id},include});this.gateway.emit(projectId,"task:created",task);return task}
 async get(projectId:string,id:string,user:AuthUser){await this.projects.requireAccess(projectId,user);const task=await this.db.task.findFirst({where:{id,projectId},include:{...include,auditLogs:{include:{user:{select:{id:true,name:true}}},orderBy:{createdAt:"desc"}}}});if(!task)throw new NotFoundException("Task not found");return task}
 async audit(projectId:string,id:string,user:AuthUser){await this.projects.requireAccess(projectId,user);if(!await this.db.task.findFirst({where:{id,projectId},select:{id:true}}))throw new NotFoundException("Task not found");return this.db.auditLog.findMany({where:{taskId:id},include:{user:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:"desc"}})}
 async update(projectId:string,id:string,user:AuthUser,body:unknown){const project=await this.projects.requireAccess(projectId,user);const current=await this.db.task.findFirst({where:{id,projectId}});if(!current)throw new NotFoundException("Task not found");const data=updateTaskDto.parse(body);const manager=project.creatorId===user.id||user.role===Role.ADMIN;if(!manager){if(current.assigneeId!==user.id)throw new ForbiddenException("Members can only update tasks assigned to themselves");if(Object.keys(data).some(field=>field!=="status")||!data.status)throw new ForbiddenException("Members can only change the status of their assigned tasks")}if(manager)await this.validateAssignee(projectId,data.assigneeId);const task=await this.db.$transaction(async tx=>{const updated=await tx.task.update({where:{id},data,include});if(data.status&&data.status!==current.status)await tx.auditLog.create({data:{taskId:id,userId:user.id,fromStatus:current.status,toStatus:data.status}});return updated});this.gateway.emit(projectId,"task:updated",task);return task}
 async remove(projectId:string,id:string,user:AuthUser){await this.projects.requireOwnerOrAdmin(projectId,user);const current=await this.db.task.findFirst({where:{id,projectId}});if(!current)throw new NotFoundException("Task not found");await this.db.task.delete({where:{id}});this.gateway.emit(projectId,"task:deleted",{id})}
}
